configserver:
  name: Docker Consul Service
  status: Connected to Consul Server running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZmMxNTcwZWNlZTUyZTdkYzNhYjUxNTM4ZDkxYTNmZTlhMzQxYTEyMDRlOTU2MzQ2MjAzYzJiNTJmYzE1ZWIyODY3MDVkOTJjMTllMjY5OGMxODc2ODY4YzIxYWFmMjM3ZWIwNWM0NTFjYWNmZDI2MzkyZTEyZDE4MmZiNmRmZTI=
